version: 2
registries:
  artifactory:
    type: npm-registry
  
updates:
  - package-ecosystem: 'npm'
    registries:
      - artifactory
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    allow:
      - dependency-type: 'all'
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-major', 'version-update:semver-minor']
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'build'
      include: 'scope'