version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "dependabot"
      - "dependencies"  
    allow:
      - dependency-type: 'all'
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-major', 'version-update:semver-minor']
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "build"
      include: "scope"
