version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "dependabot"
      - "dependencies"  
    allow:
      - dependency-type: 'production'
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "build"
      include: "scope"
