
name: Update Dependabot Pull Request Name

on: 
  push:
  label:
   types: [dependencies]

jobs:
  update_pr:
    name: PR update
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          # head-branch-regex: '[A-Za-z\d-_.\\/]+'
          title-template: '[111] '
          body-template: |
            Jira issue: 222222
            ---
          body-update-action: 'prefix'
          body-uppercase-base-match: false
