
name: Update Dependabot Pull Request Name

on: 
  push:
    # branches:    
    #   - 'dependabot-npm/**'
  label:
   types: [dependencies]

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        title-template: 'gideon'

